---
- name: Ping both nodes
  hosts: all
  gather_facts: false
  roles:
    - ping

# - name: Set up DevStack Controller
#   hosts: controller
#   become: true
#   roles:
#     - devstack_controller

# - name: Set up DevStack Compute
#   hosts: compute
#   become: true
#   roles:
#     - devstack_compute
